# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_topik',
            name='isi_topik',
            field=models.TextField(null=True),
        ),
    ]
