# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170516_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_user_subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subscribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to='forum.t_user')),
                ('email_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='forum.t_user')),
            ],
        ),
        migrations.AddField(
            model_name='t_user_grup',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
