# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170518_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_user_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.t_user')),
                ('id_topik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.t_topik')),
            ],
        ),
    ]
