# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_t_user_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_notifikasi',
            fields=[
                ('id_notifikasi', models.IntegerField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('date_created_notifikasi', models.DateTimeField(auto_now_add=True)),
                ('email_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='forum.t_user')),
                ('email_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='forum.t_user')),
                ('id_tipe_notifikasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.t_tipe_notifikasi')),
            ],
        ),
    ]
