# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_t_notifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_notifikasi',
            name='isi_notifikasi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
